apiVersion: v1
kind: Pod
metadata:
  name: app-mysql-pod
spec:
  containers:
    - name: python-app
      image: python:3.9-slim
      env:
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: PYTHONUNBUFFERED
          value: "1"
      workingDir: /app
      command: ["python", "app.py"]
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: app-volume
          mountPath: /app

    - name: mysql-db
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "SC_Group14"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "admin"
      ports:
        - containerPort: 3306
  volumes:
    - name: app-volume
      emptyDir: {}
